name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: 5000
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "evride_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/evride_test"
          directory: evride-back
          file_name: .env.test
      - name: Migrate database
        run: npx dotenv-cli -e .env.test npx prisma migrate dev --name evride_test postgres-init
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test